<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="129" started-at="2022-03-02T09:39:15 GMT+07:00" finished-at="2022-03-02T09:39:16 GMT+07:00">
    <groups>
    </groups>
    <test name="Test" duration-ms="129" started-at="2022-03-02T09:39:15 GMT+07:00" finished-at="2022-03-02T09:39:16 GMT+07:00">
      <class name="online_tusur.unit_online_tusur.NewTestNGparam">
        <test-method status="FAIL" signature="params(int,java.lang.String,java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.NewTestNGparam@a5272be]" name="params" duration-ms="16" started-at="2022-03-02T09:39:16 GMT+07:00" finished-at="2022-03-02T09:39:16 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ ] but found [Men Piter]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ ] but found [Men Piter]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.NewTestNGparam.params(NewTestNGparam.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- params -->
        <test-method status="PASS" signature="testNames(java.lang.String,java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.NewTestNGparam@a5272be]" name="testNames" duration-ms="16" started-at="2022-03-02T09:39:16 GMT+07:00" data-provider="data" finished-at="2022-03-02T09:39:16 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[petr]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Petr]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNames -->
        <test-method status="PASS" signature="testNames(java.lang.String,java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.NewTestNGparam@a5272be]" name="testNames" duration-ms="1" started-at="2022-03-02T09:39:16 GMT+07:00" data-provider="data" finished-at="2022-03-02T09:39:16 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[ivan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ivan]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNames -->
        <test-method status="PASS" signature="testNames(java.lang.String,java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.NewTestNGparam@a5272be]" name="testNames" duration-ms="5" started-at="2022-03-02T09:39:16 GMT+07:00" data-provider="data" finished-at="2022-03-02T09:39:16 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[sidor]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sidor]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNames -->
      </class> <!-- online_tusur.unit_online_tusur.NewTestNGparam -->
      <class name="online_tusur.unit_online_tusur.TestMain">
        <test-method status="FAIL" signature="testMain()[pri:0, instance:online_tusur.unit_online_tusur.TestMain@c755b2]" name="testMain" duration-ms="16" started-at="2022-03-02T09:39:16 GMT+07:00" finished-at="2022-03-02T09:39:16 GMT+07:00">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Вёселова Матрёна, 24
Nikulin Ivan, 18
Petrov Konstantin, 18
AVG= 24
MAX= 24
MIN= 18
] but found [Ivan Ivanov
MAX=25
]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Вёселова Матрёна, 24
Nikulin Ivan, 18
Petrov Konstantin, 18
AVG= 24
MAX= 24
MIN= 18
] but found [Ivan Ivanov
MAX=25
]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.TestMain.testMain(TestMain.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMain -->
      </class> <!-- online_tusur.unit_online_tusur.TestMain -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
