<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Alekseeva" name="online_tusur.unit_online_tusur.TestMain" tests="1" failures="1" timestamp="2022-03-02T09:39:16 GMT+07:00" time="0.016" errors="0">
  <testcase name="testMain" time="0.016" classname="online_tusur.unit_online_tusur.TestMain">
    <failure type="java.lang.AssertionError" message="expected [Вёселова Матрёна, 24
Nikulin Ivan, 18
Petrov Konstantin, 18
AVG= 24
MAX= 24
MIN= 18
] but found [Ivan Ivanov
MAX=25
]">
      <![CDATA[java.lang.AssertionError: expected [Вёселова Матрёна, 24
Nikulin Ivan, 18
Petrov Konstantin, 18
AVG= 24
MAX= 24
MIN= 18
] but found [Ivan Ivanov
MAX=25
]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.TestMain.testMain(TestMain.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testMain -->
  <system-out/>
</testsuite> <!-- online_tusur.unit_online_tusur.TestMain -->
